In [5]:
import pandas as pd

# Load dataset
df = pd.read_excel(r"C:\Users\amans\Downloads\Sample data (1).xlsx")

# First 5 rows
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [6]:
# Rows and columns
df.shape

(700, 16)

In [7]:
# Column names
df.columns.tolist()

['Segment',
 'Country',
 'Product',
 'Discount Band',
 'Units Sold',
 'Manufacturing Price',
 'Sale Price',
 'Gross Sales',
 'Discounts',
 ' Sales',
 'COGS',
 'Profit',
 'Date',
 'Month Number',
 'Month Name',
 'Year']

In [8]:
# Data types
df.dtypes

Segment                        object
Country                        object
Product                        object
Discount Band                  object
Units Sold                    float64
Manufacturing Price             int64
Sale Price                      int64
Gross Sales                   float64
Discounts                     float64
 Sales                        float64
COGS                          float64
Profit                        float64
Date                   datetime64[ns]
Month Number                    int64
Month Name                     object
Year                            int64
dtype: object

In [9]:
# Numerical summary
df.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,2014-04-28 21:36:00,7.900000,2013.750000
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,2013-09-01 00:00:00,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,2013-12-24 06:00:00,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,2014-05-16 12:00:00,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,2014-09-08 12:00:00,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2014-12-01 00:00:00,12.000000,2014.000000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,NaN,3.377321,0.433322

In [10]:
# Unique values in each column
df.nunique()

Segment                  5
Country                  5
Product                  6
Discount Band            3
Units Sold             510
Manufacturing Price      6
Sale Price               7
Gross Sales            550
Discounts              515
 Sales                 559
COGS                   545
Profit                 557
Date                    16
Month Number            12
Month Name              12
Year                     2
dtype: int64

In [11]:
# Missing values
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [12]:
df.corr(numeric_only=True)

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
Units Sold,1.000000,-0.029644,-6.506581e-02,0.327221,0.253048,0.326914,0.331694,0.228437,-1.036069e-01,6.385658e-02
Manufacturing Price,-0.029644,1.000000,7.078637e-02,0.049852,0.020578,0.051549,0.046857,0.061985,5.021388e-03,-9.271955e-04
Sale Price,-0.065066,0.070786,1.000000e+00,0.808250,0.641689,0.805878,0.799335,0.650495,1.742840e-16,1.829362e-13
Gross Sales,0.327221,0.049852,8.082502e-01,1.000000,0.782485,0.998174,0.994519,0.784508,-3.496563e-02,4.443489e-02
Discounts,0.253048,0.020578,6.416890e-01,0.782485,1.000000,0.743447,0.782930,0.383087,-5.359162e-02,2.239741e-02
Sales,0.326914,0.051549,8.058777e-01,0.998174,0.743447,1.000000,0.992244,0.805462,-3.235728e-02,4.555389e-02
COGS,0.331694,0.046857,7.993354e-01,0.994519,0.782930,0.992244,1.000000,0.725544,-3.615842e-02,4.731019e-02
Profit,0.228437,0.061985,6.504947e-01,0.784508,0.383087,0.805462,0.725544,1.000000,-6.743698e-03,2.663408e-02
Month Number,-0.103607,0.005021,1.742840e-16,-0.034966,-0.053592,-0.032357,-0.036158,-0.006744,1.000000e+00,-4.276786e-01
Year,0.063857,-0.000927,1.829362e-13,0.044435,0.022397,0.045554,0.047310,0.026634,-4.276786e-01,1.000000e+00

In [13]:
for col in df.select_dtypes(include="object").columns:
    print("\n", col)

 Segment

 Country

 Product

 Discount Band

 Month Name

In [14]:
   print(df[col].value_counts().head(10))

Month Name
October      140
December     105
June          70
November      70
September     70
February      35
March         35
April         35
August        35
July          35
Name: count, dtype: int64

In [15]:
print(df.columns.tolist())

['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts', ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name', 'Year']

In [16]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name', 'Year']

In [17]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 700
Number of Columns: 16

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        647 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9   Sales                700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [19]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [20]:
total_units = df["Units Sold"].sum()

print("Total Units Sold:", total_units)

Total Units Sold: 1125806.0

In [21]:
total_gross_sales = df["Gross Sales"].sum()

print("Total Gross Sales:", total_gross_sales)

Total Gross Sales: 127931598.5

In [22]:
total_discounts = df["Discounts"].sum()

print("Total Discounts:", total_discounts)

Total Discounts: 9205248.239999998

In [23]:
total_sales = df["Sales"].sum()

print("Total Sales:", total_sales)

Total Sales: 118726350.25999999

In [24]:
total_cogs = df["COGS"].sum()

print("Total COGS:", total_cogs)

Total COGS: 101832648.0

In [25]:
total_profit = df["Profit"].sum()

print("Total Profit:", total_profit)

Total Profit: 16893702.26

In [26]:
profit_margin = (total_profit / total_sales) * 100

print("Profit Margin:", round(profit_margin, 2), "%")

Profit Margin: 14.23 %

In [27]:
average_sale_price = df["Sale Price"].mean()

print("Average Sale Price:", round(average_sale_price, 2))

Average Sale Price: 118.43

In [28]:
segment_sales = (
    df.groupby("Segment")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

print(segment_sales)

Segment
Government          5.250426e+07
Small Business      4.242792e+07
Enterprise          1.961169e+07
Midmarket           2.381883e+06
Channel Partners    1.800594e+06
Name: Sales, dtype: float64

In [29]:
segment_profit = (
    df.groupby("Segment")["Profit"]
      .sum()
      .sort_values(ascending=False)
)

print(segment_profit)

Segment
Government          1.138817e+07
Small Business      4.143168e+06
Channel Partners    1.316803e+06
Midmarket           6.601031e+05
Enterprise         -6.145456e+05
Name: Profit, dtype: float64

In [30]:
segment_units = (
    df.groupby("Segment")["Units Sold"]
      .sum()
      .sort_values(ascending=False)
)

print(segment_units)

Segment
Government          470673.5
Midmarket           172178.0
Enterprise          168552.0
Channel Partners    161263.5
Small Business      153139.0
Name: Units Sold, dtype: float64

In [31]:
country_sales = (
    df.groupby("Country")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

print(country_sales)

Country
United States of America    2.502983e+07
Canada                      2.488765e+07
France                      2.435417e+07
Germany                     2.350534e+07
Mexico                      2.094935e+07
Name: Sales, dtype: float64

In [32]:
top_countries = country_sales.head(10)

print(top_countries)

Country
United States of America    2.502983e+07
Canada                      2.488765e+07
France                      2.435417e+07
Germany                     2.350534e+07
Mexico                      2.094935e+07
Name: Sales, dtype: float64

In [33]:
country_profit = (
    df.groupby("Country")["Profit"]
      .sum()
      .sort_values(ascending=False)
)

print(country_profit.head(10))

Country
France                      3781020.780
Germany                     3680388.820
Canada                      3529228.885
United States of America    2995540.665
Mexico                      2907523.110
Name: Profit, dtype: float64

In [34]:
product_sales = (
    df.groupby("Product")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

print(product_sales)

Product
Paseo        3.301114e+07
VTT          2.051192e+07
Velo         1.825006e+07
Amarilla     1.774712e+07
Montana      1.539080e+07
Carretera    1.381531e+07
Name: Sales, dtype: float64

In [35]:
top_products = product_sales.head(10)

print(top_products)

Product
Paseo        3.301114e+07
VTT          2.051192e+07
Velo         1.825006e+07
Amarilla     1.774712e+07
Montana      1.539080e+07
Carretera    1.381531e+07
Name: Sales, dtype: float64

In [36]:
product_profit = (
    df.groupby("Product")["Profit"]
      .sum()
      .sort_values(ascending=False)
)

print(product_profit.head(10))

Product
Paseo        4797437.950
VTT          3034608.020
Amarilla     2814104.060
Velo         2305992.465
Montana      2114754.880
Carretera    1826804.885
Name: Profit, dtype: float64

In [37]:
discount_sales = (
    df.groupby("Discount Band")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

print(discount_sales)

Discount Band
Medium    3.878043e+07
High      3.737249e+07
Low       3.462978e+07
Name: Sales, dtype: float64

In [38]:
discount_profit = (
    df.groupby("Discount Band")["Profit"]
      .sum()
      .sort_values(ascending=False)
)

print(discount_profit)

Discount Band
Low       6188857.700
Medium    5579522.835
High      3388866.725
Name: Profit, dtype: float64

In [39]:
average_discount = df["Discounts"].mean()

print("Average Discount:", round(average_discount, 2))

Average Discount: 13150.35

In [40]:
yearly_sales = (
    df.groupby("Year")["Sales"]
      .sum()
)

print(yearly_sales)

Year
2013    26415255.51
2014    92311094.75
Name: Sales, dtype: float64

In [41]:
yearly_profit = (
    df.groupby("Year")["Profit"]
      .sum()
)

print(yearly_profit)

Year
2013     3878464.51
2014    13015237.75
Name: Profit, dtype: float64

In [42]:
yearly_units = (
    df.groupby("Year")["Units Sold"]
      .sum()
)

print(yearly_units)

Year
2013    264674.0
2014    861132.0
Name: Units Sold, dtype: float64

In [43]:
monthly_sales = (
    df.groupby(["Month Number", "Month Name"])["Sales"]
      .sum()
      .sort_index()
)

print(monthly_sales)

Month Number  Month Name
1             January        6607761.68
2             February       7297531.39
3             March          5586859.87
4             April          6964775.07
5             May            6210211.06
6             June           9518893.82
7             July           8102920.18
8             August         5864622.42
9             September     10882697.27
10            October       21671431.02
11            November      12651417.50
12            December      17367228.98
Name: Sales, dtype: float64

In [44]:
monthly_profit = (
    df.groupby(["Month Number", "Month Name"])["Profit"]
      .sum()
      .sort_index()
)

print(monthly_profit)

Month Number  Month Name
1             January        814028.68
2             February      1148547.39
3             March          669866.87
4             April          929984.57
5             May            828640.06
6             June          1473753.82
7             July           923865.68
8             August         791066.42
9             September     1786735.27
10            October       3439781.02
11            November      1370102.50
12            December      2717329.98
Name: Profit, dtype: float64

In [45]:
best_segment = segment_sales.idxmax()
best_segment_sales = segment_sales.max()

print("Best Segment:", best_segment)
print("Sales:", best_segment_sales)

Best Segment: Government
Sales: 52504260.67

In [46]:
best_profit_segment = segment_profit.idxmax()
best_profit = segment_profit.max()

print("Most Profitable Segment:", best_profit_segment)
print("Profit:", best_profit)

Most Profitable Segment: Government
Profit: 11388173.17

In [47]:
best_profit_country = country_profit.idxmax()
best_country_profit = country_profit.max()

print("Most Profitable Country:", best_profit_country)
print("Profit:", best_country_profit)

Most Profitable Country: France
Profit: 3781020.78

In [48]:
best_product = product_sales.idxmax()
best_product_sales = product_sales.max()

print("Best Product:", best_product)
print("Sales:", best_product_sales)

Best Product: Paseo
Sales: 33011143.95

In [49]:
best_profit_product = product_profit.idxmax()
best_product_profit = product_profit.max()

print("Most Profitable Product:", best_profit_product)
print("Profit:", best_product_profit)

Most Profitable Product: Paseo
Profit: 4797437.95

In [50]:
numeric_columns = [
    "Units Sold",
    "Manufacturing Price",
    "Sale Price",
    "Gross Sales",
    "Discounts",
    "Sales",
    "COGS",
    "Profit"
]

correlation = df[numeric_columns].corr()

correlation

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit
Units Sold,1.000000,-0.029644,-0.065066,0.327221,0.253048,0.326914,0.331694,0.228437
Manufacturing Price,-0.029644,1.000000,0.070786,0.049852,0.020578,0.051549,0.046857,0.061985
Sale Price,-0.065066,0.070786,1.000000,0.808250,0.641689,0.805878,0.799335,0.650495
Gross Sales,0.327221,0.049852,0.808250,1.000000,0.782485,0.998174,0.994519,0.784508
Discounts,0.253048,0.020578,0.641689,0.782485,1.000000,0.743447,0.782930,0.383087
Sales,0.326914,0.051549,0.805878,0.998174,0.743447,1.000000,0.992244,0.805462
COGS,0.331694,0.046857,0.799335,0.994519,0.782930,0.992244,1.000000,0.725544
Profit,0.228437,0.061985,0.650495,0.784508,0.383087,0.805462,0.725544,1.000000

In [51]:
kpi_summary = {
    "Total Units Sold": df["Units Sold"].sum(),
    "Total Gross Sales": df["Gross Sales"].sum(),
    "Total Discounts": df["Discounts"].sum(),
    "Total Sales": df["Sales"].sum(),
    "Total COGS": df["COGS"].sum(),
    "Total Profit": df["Profit"].sum(),
    "Average Sale Price": df["Sale Price"].mean(),
    "Profit Margin (%)": (df["Profit"].sum() / df["Sales"].sum()) * 100
}

kpi_summary

{'Total Units Sold': 1125806.0,
 'Total Gross Sales': 127931598.5,
 'Total Discounts': 9205248.239999998,
 'Total Sales': 118726350.25999999,
 'Total COGS': 101832648.0,
 'Total Profit': 16893702.26,
 'Average Sale Price': 118.42857142857143,
 'Profit Margin (%)': 14.229109395685388}